#! /bin/sh

PATH=/sbin:/bin
export PATH

mount -t proc proc /proc
/bin/mount -a

case "$(cat /etc/model_name)" in
	"XG6846")
		echo /sbin/hotplug-call > /proc/sys/kernel/hotplug
		break
		;;
	*)
		;;
esac
