#ifndef __MDM_OBJECTID_H__
#define __MDM_OBJECTID_H__


/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*!\file mdm_objectid.h 
 * \brief Automatically generated header file mdm_objectid.h
 */


/*! \brief InternetGatewayDevice. */
#define MDMOID_IGD  1

/*! \brief InternetGatewayDevice.X_XAVI_COM_XmlProvisionCfg. */
#define MDMOID_XML_PROVISION_CFG  2

/*! \brief InternetGatewayDevice.X_XAVI_COM_InternetPortCfg. */
#define MDMOID_INTERNET_PORT_CFG  3

/*! \brief InternetGatewayDevice.X_XAVI_COM_Enbl8021pQosCfg. */
#define MDMOID_ENBL8021P_QOS_CFG  4

/*! \brief InternetGatewayDevice.X_XAVI_COM_PortModeCfg. */
#define MDMOID_PORT_MODE_CFG  5

/*! \brief InternetGatewayDevice.X_XAVI_COM_CatvCfg. */
#define MDMOID_CATV_CFG  6

/*! \brief InternetGatewayDevice.X_XAVI_COM_QinQCfg. */
#define MDMOID_QIN_Q_CFG  7

/*! \brief InternetGatewayDevice.X_XAVI_COM_PortPowerCfg. */
#define MDMOID_PORT_POWER  8

/*! \brief InternetGatewayDevice.X_XAVI_COM. */
#define MDMOID_XAVI_CFG  9

/*! \brief InternetGatewayDevice.X_XAVI_COM_JumboModeCfg. */
#define MDMOID_JUMBO_MODE_CFG  10

/*! \brief InternetGatewayDevice.X_XAVI_COM_PortProtectCfg. */
#define MDMOID_PORT_PROTECT_CFG  11

/*! \brief InternetGatewayDevice.X_XAVI_COM_VlanCfg. */
#define MDMOID_VLAN_CFG  12

/*! \brief InternetGatewayDevice.X_XAVI_COM_QosListCfg. */
#define MDMOID_QOS_LIST_CFG  13

/*! \brief InternetGatewayDevice.X_XAVI_COM_RateLimitingCfg. */
#define MDMOID_RATE_LIMITING  14

/*! \brief InternetGatewayDevice.X_XAVI_COM_LANDevice.{i}. */
#define MDMOID_XAVI_LAN_DEV  15

/*! \brief InternetGatewayDevice.X_XAVI_COM_LANDevice.{i}.LANPortConfig.{i}. */
#define MDMOID_LAN_PORT  16

/*! \brief InternetGatewayDevice.X_XAVI_COM_LANDevice.{i}.LANPortConfig.{i}.Stats. */
#define MDMOID_LAN_PORT_STATS  17

/*! \brief InternetGatewayDevice.X_XAVI_COM_PortMacCfg. */
#define MDMOID_PORT_MAC_CFG  18

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_ServiceCtrlCfg. */
#define MDMOID_SERVICE_CTRL_CFG  19

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IpAccCfg. */
#define MDMOID_IP_ACC  20

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IpAccCfg.X_BROADCOM_COM_IpAccListCfgObj.{i}. */
#define MDMOID_IP_ACC_LIST  21

/*! \brief InternetGatewayDevice.X_XAVI_COM_IgmpCfg. */
#define MDMOID_IGMP_SNOOPING_ENABLE_CFG  22

/*! \brief InternetGatewayDevice.X_XAVI_COM_LedCfg. */
#define MDMOID_LED_CFG  23

/*! \brief InternetGatewayDevice.DeviceInfo. */
#define MDMOID_IGD_DEVICE_INFO  24

/*! \brief InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}. */
#define MDMOID_VENDOR_CONFIG_FILE  25

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_BpaApiFlowHandle.{i}. */
#define MDMOID_BPA_API_FLOW_HANDLE  26

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SyslogCfg. */
#define MDMOID_SYSLOG_CFG  27

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_LoginCfg. */
#define MDMOID_LOGIN_CFG  28

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg. */
#define MDMOID_APP_CFG  29

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.HttpdCfg. */
#define MDMOID_HTTPD_CFG  30

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.Tr69cCfg. */
#define MDMOID_TR69C_CFG  31

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.Tr64cCfg. */
#define MDMOID_TR64C_CFG  32

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SshdCfg. */
#define MDMOID_SSHD_CFG  33

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.TelnetdCfg. */
#define MDMOID_TELNETD_CFG  34

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.ConsoledCfg. */
#define MDMOID_CONSOLED_CFG  35

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SmdCfg. */
#define MDMOID_SMD_CFG  36

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SskCfg. */
#define MDMOID_SSK_CFG  37

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SnmpdCfg. */
#define MDMOID_SNMPD_CFG  38

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.FtpdCfg. */
#define MDMOID_FTPD_CFG  39

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.TftpdCfg. */
#define MDMOID_TFTPD_CFG  40

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.PppdCfg. */
#define MDMOID_PPPD_CFG  41

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.IcmpCfg. */
#define MDMOID_ICMP_CFG  42

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.UpnpCfg. */
#define MDMOID_UPNP_CFG  43

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.DnsProxyCfg. */
#define MDMOID_DNS_PROXY_CFG  44

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.DectdCfg. */
#define MDMOID_DECTD_CFG  45

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.VectoringCfg. */
#define MDMOID_VECTORING_CFG  46

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OmcidCfg. */
#define MDMOID_OMCID_CFG  47

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OmciPmdCfg. */
#define MDMOID_OMCI_PMD_CFG  48

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OsgidCfg. */
#define MDMOID_OSGID_CFG  49

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_EthernetSwitch. */
#define MDMOID_ETHERNET_SWITCH  50

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_PwrMngtCfg. */
#define MDMOID_PWR_MNGT  51

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_StandbyCfg. */
#define MDMOID_STANDBY_CFG  52

/*! \brief InternetGatewayDevice.DeviceConfig. */
#define MDMOID_DEVICE_CONFIG  53

/*! \brief InternetGatewayDevice.ManagementServer. */
#define MDMOID_MANAGEMENT_SERVER  54

/*! \brief InternetGatewayDevice.ManagementServer.ManageableDevice.{i}. */
#define MDMOID_MANAGEABLE_DEVICE  55

/*! \brief InternetGatewayDevice.Time. */
#define MDMOID_TIME_SERVER_CFG  56

/*! \brief InternetGatewayDevice.Layer2Bridging. */
#define MDMOID_L2_BRIDGING  57

/*! \brief InternetGatewayDevice.Layer2Bridging.Bridge.{i}. */
#define MDMOID_L2_BRIDGING_ENTRY  58

/*! \brief InternetGatewayDevice.Layer2Bridging.Filter.{i}. */
#define MDMOID_L2_BRIDGING_FILTER  59

/*! \brief InternetGatewayDevice.Layer2Bridging.AvailableInterface.{i}. */
#define MDMOID_L2_BRIDGING_INTF  60

/*! \brief InternetGatewayDevice.QueueManagement. */
#define MDMOID_Q_MGMT  61

/*! \brief InternetGatewayDevice.QueueManagement.Classification.{i}. */
#define MDMOID_Q_MGMT_CLASSIFICATION  62

/*! \brief InternetGatewayDevice.QueueManagement.Policer.{i}. */
#define MDMOID_Q_MGMT_POLICER  63

/*! \brief InternetGatewayDevice.QueueManagement.Queue.{i}. */
#define MDMOID_Q_MGMT_QUEUE  64

/*! \brief InternetGatewayDevice.IPPingDiagnostics. */
#define MDMOID_IP_PING_DIAG  65

/*! \brief InternetGatewayDevice.EponSoftwareImage.{i}. */
#define MDMOID_EPON_SOFTWARE_IMAGE  66

/*! \brief InternetGatewayDevice.EponSwUpgradeStatus. */
#define MDMOID_EPON_SW_UPGRADE_STATUS  67

/*! \brief InternetGatewayDevice.LANDevice.{i}. */
#define MDMOID_LAN_DEV  68

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IgmpSnoopingConfig. */
#define MDMOID_IGMP_SNOOPING_CFG  69

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement. */
#define MDMOID_LAN_HOST_CFG  70

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}. */
#define MDMOID_LAN_IP_INTF  71

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_IPv6LanIntfAddress. */
#define MDMOID_I_PV6_LAN_INTF_ADDR  72

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_IPv6LanIntfAddress.DelegatedAddress.{i}. */
#define MDMOID_DELEGATED_ADDRESS  73

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_LAN_IP_INTF_FIREWALL_EXCEPTION  74

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_IpFilterCfg.{i}. */
#define MDMOID_IP_FILTER_CFG  75

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}. */
#define MDMOID_DHCP_CONDITIONAL_SERVING  76

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement. */
#define MDMOID_I_PV6_LAN_HOST_CFG  77

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.RadvdConfigManagement. */
#define MDMOID_RADVD_CONFIG_MGT  78

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.RadvdConfigManagement.ULAPrefixInfo. */
#define MDMOID_ULA_PREFIX_INFO  79

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.RadvdConfigManagement.PrefixInformation.{i}. */
#define MDMOID_PREFIX_INFO  80

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.X_BROADCOM_COM_MldSnoopingConfig. */
#define MDMOID_MLD_SNOOPING_CFG  81

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}. */
#define MDMOID_LAN_ETH_INTF  82

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_ETH_INTF_STATS  83

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}. */
#define MDMOID_LAN_USB_INTF  84

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_USB_INTF_STATS  85

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}. */
#define MDMOID_LAN_WLAN  86

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.AssociatedDevice.{i}. */
#define MDMOID_LAN_WLAN_ASSOCIATED_DEVICE_ENTRY  87

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}. */
#define MDMOID_LAN_WLAN_WEP_KEY  88

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}. */
#define MDMOID_LAN_WLAN_PRE_SHARED_KEY  89

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter. */
#define MDMOID_WLAN_ADAPTER  90

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlBaseCfg. */
#define MDMOID_WL_BASE_CFG  91

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlStaticWdsCfg.{i}. */
#define MDMOID_WL_STATIC_WDS_CFG  92

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlWdsCfg.{i}. */
#define MDMOID_WL_WDS_CFG  93

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlScanWdsCfg.{i}. */
#define MDMOID_WL_SCAN_WDS_CFG  94

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlMimoCfg. */
#define MDMOID_WL_MIMO_CFG  95

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlSesCfg. */
#define MDMOID_WL_SES_CFG  96

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlVirtIntfCfg.{i}. */
#define MDMOID_WL_VIRT_INTF_CFG  97

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlMacFltCfg.{i}. */
#define MDMOID_WL_MAC_FLT  98

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlKey64Cfg.{i}. */
#define MDMOID_WL_KEY64_CFG  99

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlKey128Cfg.{i}. */
#define MDMOID_WL_KEY128_CFG  100

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlWpsCfg. */
#define MDMOID_WL_WPS_CFG  101

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}. */
#define MDMOID_LAN_MOCA_INTF  102

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}.Status. */
#define MDMOID_LAN_MOCA_INTF_STATUS  103

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_MOCA_INTF_STATS  104

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANEponInterfaceConfig.{i}. */
#define MDMOID_LAN_EPON_INTF  105

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANEponInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_EPON_INTF_STATS  106

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts. */
#define MDMOID_LAN_HOSTS  107

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}. */
#define MDMOID_LAN_HOST_ENTRY  108

/*! \brief InternetGatewayDevice.WANDevice.{i}. */
#define MDMOID_WAN_DEV  109

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig. */
#define MDMOID_WAN_COMMON_INTF_CFG  110

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_XTM_Interface_Stats.{i}. */
#define MDMOID_XTM_INTERFACE_STATS  111

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig. */
#define MDMOID_WAN_DSL_INTF_CFG  112

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.X_BROADCOM_COM_BertTest. */
#define MDMOID_WAN_BERT_TEST  113

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats. */
#define MDMOID_WAN_DSL_INTF_STATS  114

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Total. */
#define MDMOID_WAN_DSL_INTF_STATS_TOTAL  115

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Showtime. */
#define MDMOID_WAN_DSL_INTF_STATS_SHOWTIME  116

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.CurrentDay. */
#define MDMOID_WAN_DSL_INTF_STATS_CURRENT_DAY  117

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.QuarterHour. */
#define MDMOID_WAN_DSL_INTF_STATS_QUARTER_HOUR  118

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.TestParams. */
#define MDMOID_WAN_DSL_TEST_PARAMS  119

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig. */
#define MDMOID_WAN_ETH_INTF  120

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.X_BROADCOM_COM_IPv6Address.{i}. */
#define MDMOID_I_PV6_ADDR  121

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.Stats. */
#define MDMOID_WAN_ETH_INTF_STATS  122

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig. */
#define MDMOID_WAN_MOCA_INTF  123

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig.Status. */
#define MDMOID_WAN_MOCA_INTF_STATUS  124

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig.Stats. */
#define MDMOID_WAN_MOCA_INTF_STATS  125

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_EponInterfaceConfig. */
#define MDMOID_WAN_EPON_INTF  126

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_EponInterfaceConfig.Stats. */
#define MDMOID_WAN_EPON_INTF_STATS  127

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_L2tpAcIntfConfig. */
#define MDMOID_L2TP_AC_INTF_CONFIG  128

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANPonInterfaceConfig. */
#define MDMOID_WAN_PON_INTF  129

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANPonInterfaceConfig.Stats. */
#define MDMOID_WAN_PON_INTF_STATUS  130

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_DIAG  131

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_PROPRIETARY_DIAG  132

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics.PeakLineNoise. */
#define MDMOID_WAN_DSL_DIAG_PLN  133

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics.NonLinearity. */
#define MDMOID_WAN_DSL_DIAG_NON_LINEARITY  134

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}. */
#define MDMOID_WAN_CONN_DEVICE  135

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF4EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_END_TO_END_LOOPBACK_DIAG  136

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF4LoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_LOOPBACK_DIAG  137

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF5EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F5_END_TO_END_LOOPBACK_DIAG  138

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANGPONLinkConfig. */
#define MDMOID_WAN_GPON_LINK_CFG  139

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANEPONLinkConfig. */
#define MDMOID_WAN_EPON_LINK_CFG  140

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig. */
#define MDMOID_WAN_DSL_LINK_CFG  141

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig.X_BROADCOM_COM_ATM_PARMS. */
#define MDMOID_WAN_DSL_ATM_PARAMS  142

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANATMF5LoopbackDiagnostics. */
#define MDMOID_WAN_ATM5_LOOPBACK_DIAG  143

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPTMLinkConfig. */
#define MDMOID_WAN_PTM_LINK_CFG  144

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANEthernetLinkConfig. */
#define MDMOID_WAN_ETH_LINK_CFG  145

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_L2tpAcLinkConfig. */
#define MDMOID_L2TP_AC_LINK_CONFIG  146

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}. */
#define MDMOID_WAN_IP_CONN  147

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_IP_CONN_PORTMAPPING  148

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_PortTriggering.{i}. */
#define MDMOID_WAN_IP_CONN_PORT_TRIGGERING  149

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_WAN_IP_CONN_FIREWALL_EXCEPTION  150

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_MacFilterObj. */
#define MDMOID_MAC_FILTER  151

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_MacFilterObj.X_BROADCOM_COM_MacFilterCfg.{i}. */
#define MDMOID_MAC_FILTER_CFG  152

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.Stats. */
#define MDMOID_WAN_IP_CONN_STATS  153

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}. */
#define MDMOID_WAN_PPP_CONN  154

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_PPP_CONN_PORTMAPPING  155

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_BROADCOM_COM_PortTriggering.{i}. */
#define MDMOID_WAN_PPP_CONN_PORT_TRIGGERING  156

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_WAN_PPP_CONN_FIREWALL_EXCEPTION  157

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.Stats. */
#define MDMOID_WAN_PPP_CONN_STATS  158

/*! \brief InternetGatewayDevice.Layer3Forwarding. */
#define MDMOID_L3_FORWARDING  159

/*! \brief InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}. */
#define MDMOID_L3_FORWARDING_ENTRY  160

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPv6Layer3Forwarding. */
#define MDMOID_I_PV6_L3_FORWARDING  161

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPv6Layer3Forwarding.IPv6Forwarding.{i}. */
#define MDMOID_I_PV6_L3_FORWARDING_ENTRY  162

/*! \brief InternetGatewayDevice.Services. */
#define MDMOID_SERVICES  163

/*! \brief InternetGatewayDevice.Services.StorageService.{i}. */
#define MDMOID_STORAGE_SERVICE  164

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.UserAccount.{i}. */
#define MDMOID_USER_ACCOUNT  165

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.Capabilites. */
#define MDMOID_CAPABILITES  166

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetInfo. */
#define MDMOID_NETWORK_INFO  167

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetworkServer. */
#define MDMOID_NETWORK_SERVER  168

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.PhysicalMedium.{i}. */
#define MDMOID_PHYSICAL_MEDIUM  169

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}. */
#define MDMOID_LOGICAL_VOLUME  170

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}.Folder.{i}. */
#define MDMOID_FOLDER  171

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}. */
#define MDMOID_VOICE  172

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}. */
#define MDMOID_VOICE_CALL_LIST  173

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.NewFlag. */
#define MDMOID_VOICE_CALL_NEW_FLAG  174

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.NumberOfMissedCalls. */
#define MDMOID_VOICE_CALL_NUMBER_OF_MISSED_CALLS  175

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.Number. */
#define MDMOID_VOICE_CALL_NUMBER  176

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.Name. */
#define MDMOID_VOICE_CALL_NAME  177

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.DateTime. */
#define MDMOID_VOICE_CALL_DATE_TIME  178

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.LineName. */
#define MDMOID_VOICE_CALL_LINE_NAME  179

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.LineId. */
#define MDMOID_VOICE_CALL_LINE_ID  180

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.CallType. */
#define MDMOID_VOICE_CALL_TYPE  181

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_InternalName.{i}. */
#define MDMOID_VOICE_INTERNAL_NAME_LIST  182

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_InternalName.{i}.TerminalNumber. */
#define MDMOID_VOICE_TERMINAL_NUMBER  183

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_InternalName.{i}.Name. */
#define MDMOID_VOICE_INTERNAL_NAME  184

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}. */
#define MDMOID_VOICE_CONTACT_LIST  185

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.Name. */
#define MDMOID_VOICE_CONTACT_NAME  186

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.FirstName. */
#define MDMOID_VOICE_CONTACT_FIRST_NAME  187

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.ContactNumber. */
#define MDMOID_VOICE_CONTACT_NUMBER  188

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.Melody. */
#define MDMOID_VOICE_CONTACT_MELODY  189

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.LineId. */
#define MDMOID_VOICE_CONTACT_LINE_ID  190

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_SupportList.{i}. */
#define MDMOID_VOICE_DECT_SUPPORT_LIST  191

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities. */
#define MDMOID_VOICE_CAP  192

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.SIP. */
#define MDMOID_VOICE_CAP_SIP  193

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.MGCP. */
#define MDMOID_VOICE_CAP_MGCP  194

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.Codecs.{i}. */
#define MDMOID_VOICE_CAP_CODECS  195

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}. */
#define MDMOID_VOICE_PROF  196

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.ServiceProviderInfo. */
#define MDMOID_VOICE_PROF_PROVIDER  197

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP. */
#define MDMOID_VOICE_PROF_SIP  198

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP.EventSubscribe.{i}. */
#define MDMOID_VOICE_PROF_SIP_SUBSCRIBE  199

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.MGCP. */
#define MDMOID_VOICE_PROF_MGCP  200

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP. */
#define MDMOID_VOICE_PROF_RTP  201

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP.SRTP. */
#define MDMOID_VOICE_PROF_RTP_SRTP  202

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.FaxT38. */
#define MDMOID_VOICE_PROF_FAX_T38  203

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}. */
#define MDMOID_VOICE_LINE  204

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.SIP. */
#define MDMOID_VOICE_LINE_SIP  205

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.CallingFeatures. */
#define MDMOID_VOICE_LINE_CALLING_FEATURES  206

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.VoiceProcessing. */
#define MDMOID_VOICE_LINE_PROCESSING  207

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec. */
#define MDMOID_VOICE_LINE_CODEC  208

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec.List.{i}. */
#define MDMOID_VOICE_LINE_CODEC_LIST  209

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Stats. */
#define MDMOID_VOICE_LINE_STATS  210

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_LineSetting. */
#define MDMOID_VOICE_LINE_SETTING  211

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.LineName. */
#define MDMOID_VOICE_LINE_NAME  212

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.LineId. */
#define MDMOID_VOICE_LINE_DECT_LINE_ID  213

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.AttachedHandset. */
#define MDMOID_VOICE_LINE_ATTACHED_HANDSET  214

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.Melody. */
#define MDMOID_VOICE_LINE_MELODY  215

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.DialingPrefix. */
#define MDMOID_VOICE_LINE_DIALING_PREFIX  216

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.Volumn. */
#define MDMOID_VOICE_LINE_VOLUMN  217

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.BlockedNumber. */
#define MDMOID_VOICE_LINE_BLOCKED_NUMBER  218

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.MultiCallMode. */
#define MDMOID_VOICE_LINE_MULTI_CALL_MODE  219

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.IntrusionCall. */
#define MDMOID_VOICE_LINE_INTRUSION_CALL  220

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.CLIR. */
#define MDMOID_CLI_R  221

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.CallForwarding. */
#define MDMOID_VOICE_LINE_CALL_FORWARDING  222

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}. */
#define MDMOID_VOICE_PHY_INTF  223

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}.Tests. */
#define MDMOID_VOICE_PHY_INTF_TESTS  224

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_PSTN.{i}. */
#define MDMOID_VOICE_PSTN  225

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Ntr. */
#define MDMOID_VOICE_NTR  226

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Ntr.History.{i}. */
#define MDMOID_VOICE_NTR_HISTORY  227

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface. */
#define MDMOID_VOICE_DECT_SYSTEM_SETTING  228

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.Handset.{i}. */
#define MDMOID_DECT_HANDSET  229

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.PINCode. */
#define MDMOID_VOICE_DECT_PIN_CODE  230

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ClockMaster. */
#define MDMOID_VOICE_DECT_CLOCK_MASTER  231

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ResetBase. */
#define MDMOID_VOICE_DECT_RESET_BASE  232

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.FirmwareVersion. */
#define MDMOID_VOICE_DECT_FIRMWARE_VERSION  233

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.HardwareVersion. */
#define MDMOID_VOICE_DECT_HARDWARE_VERSION  234

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.EEPROMVersion. */
#define MDMOID_EEPROM_VERSION  235

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SnmpCfg. */
#define MDMOID_SNMP_CFG  236

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SecDmzHostCfg. */
#define MDMOID_SEC_DMZ_HOST_CFG  237

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AccessTimeRestriction.{i}. */
#define MDMOID_ACCESS_TIME_RESTRICTION  238

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_UrlFilterCfg. */
#define MDMOID_URL_FILTER_CFG  239

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_UrlFilterCfg.X_BROADCOM_COM_UrlFilterListCfgObj.{i}. */
#define MDMOID_URL_FILTER_LIST  240

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DDnsCfg.{i}. */
#define MDMOID_D_DNS_CFG  241

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPPCfg. */
#define MDMOID_IPP_CFG  242

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DLNA. */
#define MDMOID_DLNA  243

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DLNA.DmsCfg. */
#define MDMOID_DMS_CFG  244

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DebugPortMirroringCfg.{i}. */
#define MDMOID_WAN_DEBUG_PORT_MIRRORING_CFG  245

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPSecCfg.{i}. */
#define MDMOID_IP_SEC_CFG  246

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_CertificateCfg.{i}. */
#define MDMOID_CERTIFICATE_CFG  247

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate. */
#define MDMOID_WAPI_CERTIFICATE  248

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate.WapiAsCertificate. */
#define MDMOID_WAPI_AS_CERTIFICATE  249

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate.WapiIssuedCertificate. */
#define MDMOID_WAPI_ISSUED_CERTIFICATE  250

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_NetworkConfig. */
#define MDMOID_NETWORK_CONFIG  251

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_InterfaceControl. */
#define MDMOID_INTERFACE_CONTROL  252

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_P8021agCfg. */
#define MDMOID_P8021AG_CFG  253

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IGMPCfg. */
#define MDMOID_IGMP_CFG  254

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_MLDCfg. */
#define MDMOID_MLD_CFG  255

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPTunnel.{i}. */
#define MDMOID_IP_TUNNEL  256

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPTunnel.{i}.V4inV6Tunnel.{i}. */
#define MDMOID_IPV4IN_IPV6_TUNNEL  257

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPTunnel.{i}.V6inV4Tunnel.{i}. */
#define MDMOID_IPV6IN_IPV4_TUNNEL  258

/*! \brief InternetGatewayDevice.X_ITU_T_ORG. */
#define MDMOID_ITU_T_ORG  259

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4. */
#define MDMOID_G_984_4  260

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement. */
#define MDMOID_EQUIPMENT_MANAGEMENT  261

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntG. */
#define MDMOID_ONT_G  262

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.Ont2G. */
#define MDMOID_ONT2_G  263

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntData. */
#define MDMOID_ONT_DATA  264

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.SoftwareImage.{i}. */
#define MDMOID_SOFTWARE_IMAGE  265

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CardHolder.{i}. */
#define MDMOID_CARD_HOLDER  266

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CircuitPack.{i}. */
#define MDMOID_CIRCUIT_PACK  267

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PowerShedding.{i}. */
#define MDMOID_POWER_SHEDDING  268

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PortMappingPackageG.{i}. */
#define MDMOID_PORT_MAPPING_PACKAGE_G  269

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement. */
#define MDMOID_ANI_MANAGEMENT  270

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.AniG.{i}. */
#define MDMOID_ANI_G  271

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.TCont.{i}. */
#define MDMOID_T_CONT  272

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortNetworkCtp.{i}. */
#define MDMOID_GEM_PORT_NETWORK_CTP  273

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemInterworkingTp.{i}. */
#define MDMOID_GEM_INTERWORKING_TP  274

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}. */
#define MDMOID_MULTICAST_GEM_INTERWORKING_TP  275

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}.MulticastAddressTable.{i}. */
#define MDMOID_GEM_INTERWORKING_TP_MULTICAST_ADDRESS_TABLE  276

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortPmHistoryData.{i}. */
#define MDMOID_GEM_PORT_PM_HISTORY_DATA  277

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetProfile.{i}. */
#define MDMOID_GAL_ETHERNET_PROFILE  278

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetPmHistoryData.{i}. */
#define MDMOID_GAL_ETHERNET_PM_HISTORY_DATA  279

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.FecPmHistoryData.{i}. */
#define MDMOID_FEC_PM_HISTORY_DATA  280

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices. */
#define MDMOID_LAYER2_DATA_SERVICES  281

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeServiceProfile.{i}. */
#define MDMOID_MAC_BRIDGE_SERVICE_PROFILE  282

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MacBridgeServiceProfile.{i}. */
#define MDMOID_BC_MAC_BRIDGE_SERVICE_PROFILE  283

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_CONFIG_DATA  284

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PM_HISTORY_DATA  285

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_CONFIG_DATA  286

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortDesignationData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_DESIGNATION_DATA  287

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_TABLE_DATA  288

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}.MacFilterTable.{i}. */
#define MDMOID_MAC_FILTER_TABLE  289

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterPreAssignTable.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_PRE_ASSIGN_TABLE  290

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_BRIDGE_TABLE_DATA  291

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}.BridgeTable.{i}. */
#define MDMOID_BRIDGE_TABLE  292

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortPmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_PM_HISTORY_DATA  293

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MapperServiceProfile.{i}. */
#define MDMOID_MAPPER_SERVICE_PROFILE  294

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MapperServiceProfile.{i}. */
#define MDMOID_BC_MAPPER_SERVICE_PROFILE  295

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingFilterData.{i}. */
#define MDMOID_VLAN_TAGGING_FILTER_DATA  296

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  297

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_EXTENDED_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  298

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}.ReceivedFrameVlanTaggingOperationTable.{i}. */
#define MDMOID_RECEIVED_FRAME_VLAN_TAGGING_OPERATION_TABLE  299

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}. */
#define MDMOID_MULTICAST_OPERATIONS_PROFILE  300

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.DynamicAccessControlListTable.{i}. */
#define MDMOID_DYNAMIC_ACCESS_CONTROL_LIST_TABLE  301

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.StaticAccessControlListTable.{i}. */
#define MDMOID_STATIC_ACCESS_CONTROL_LIST_TABLE  302

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.LostGroupsListTable.{i}. */
#define MDMOID_LOST_GROUPS_LIST_TABLE  303

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberConfigInfo.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_CONFIG_INFO  304

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_MONITOR  305

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}.ActiveGroupsListTable.{i}. */
#define MDMOID_ACTIVE_GROUPS_LIST_TABLE  306

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MulticastSubscriberMonitor.{i}. */
#define MDMOID_BC_MULTICAST_SUBSCRIBER_MONITOR  307

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MulticastSubscriberMonitor.{i}.MulticastSubscriber.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER  308

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.UpstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_UPSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  309

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.DownstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_DOWNSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  310

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices. */
#define MDMOID_LAYER3_DATA_SERVICES  311

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostConfigData.{i}. */
#define MDMOID_IP_HOST_CONFIG_DATA  312

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_BROADCOM_COM_IpHostConfigData.{i}. */
#define MDMOID_BC_IP_HOST_CONFIG_DATA  313

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostPmHistoryData.{i}. */
#define MDMOID_IP_HOST_PM_HISTORY_DATA  314

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}. */
#define MDMOID_IPV6_HOST_CONFIG_DATA  315

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentAddressTable.{i}. */
#define MDMOID_IPV6_CURRENT_ADDRESS_TABLE  316

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDefaultRouterTable.{i}. */
#define MDMOID_IPV6_CURRENT_DEFAULT_ROUTER_TABLE  317

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDnsTable.{i}. */
#define MDMOID_IPV6_CURRENT_DNS_TABLE  318

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentOnlinkPrefixTable.{i}. */
#define MDMOID_IPV6_CURRENT_ONLINK_PREFIX_TABLE  319

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_BROADCOM_COM_Ipv6HostConfigData.{i}. */
#define MDMOID_BC_IPV6_HOST_CONFIG_DATA  320

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.TcpUdpConfigData.{i}. */
#define MDMOID_TCP_UDP_CONFIG_DATA  321

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices. */
#define MDMOID_ETHERNET_SERVICES  322

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.PptpEthernetUni.{i}. */
#define MDMOID_PPTP_ETHERNET_UNI  323

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA  324

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData2.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA2  325

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData3.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA3  326

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.VirtualEthernetInterfacePoint.{i}. */
#define MDMOID_VIRTUAL_ETHERNET_INTERFACE_POINT  327

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices. */
#define MDMOID_VOICE_SERVICES  328

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.PptpPotsUni.{i}. */
#define MDMOID_PPTP_POTS_UNI  329

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipUserData.{i}. */
#define MDMOID_SIP_USER_DATA  330

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentConfigData.{i}. */
#define MDMOID_SIP_AGENT_CONFIG_DATA  331

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpVoiceCtp.{i}. */
#define MDMOID_VO_IP_VOICE_CTP  332

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpMediaProfile.{i}. */
#define MDMOID_VO_IP_MEDIA_PROFILE  333

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceServiceProfile.{i}. */
#define MDMOID_VOICE_SERVICE  334

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpProfileData.{i}. */
#define MDMOID_RTP_PROFILE_DATA  335

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpAppServiceProfile.{i}. */
#define MDMOID_VO_IP_APP_SERVICE_PROFILE  336

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceFeatureAccessCodes.{i}. */
#define MDMOID_VOICE_FEATURE_ACCESS_CODES  337

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}. */
#define MDMOID_NETWORK_DIAL_PLAN_TABLE  338

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}.DialPlanTable.{i}. */
#define MDMOID_DIAL_PLAN_TABLE  339

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpLineStatus.{i}. */
#define MDMOID_VO_IP_LINE_STATUS  340

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.CallControlPmHistoryData.{i}. */
#define MDMOID_CALL_CONTROL_PM_HISTORY_DATA  341

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpPmHistoryData.{i}. */
#define MDMOID_RTP_PM_HISTORY_DATA  342

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentPmHistoryData.{i}. */
#define MDMOID_SIP_AGENT_PM_HISTORY_DATA  343

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipCallInitPmHistoryData.{i}. */
#define MDMOID_SIP_CALL_INIT_PM_HISTORY_DATA  344

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcConfigData.{i}. */
#define MDMOID_MGC_CONFIG_DATA  345

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcPmHistoryData.{i}. */
#define MDMOID_MGC_PM_HISTORY_DATA  346

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpConfigData.{i}. */
#define MDMOID_VO_IP_CONFIG_DATA  347

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices. */
#define MDMOID_MOCA_SERVICES  348

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.PptpMocaUni.{i}. */
#define MDMOID_PPTP_MOCA_UNI  349

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_PptpMocaUni.{i}. */
#define MDMOID_BRCM_PPTP_MOCA_UNI  350

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_MocaStatus.{i}. */
#define MDMOID_MOCA_STATUS  351

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_MocaStats.{i}. */
#define MDMOID_MOCA_STATS  352

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaEthernetPmHistoryData.{i}. */
#define MDMOID_MOCA_ETHERNET_PM_HISTORY_DATA  353

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA  354

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}.NodeTable.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA_NODE_TABLE  355

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement. */
#define MDMOID_TRAFFIC_MANAGEMENT  356

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.PriorityQueueG.{i}. */
#define MDMOID_PRIORITY_QUEUE_G  357

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.TrafficSchedulerG.{i}. */
#define MDMOID_TRAFFIC_SCHEDULER_G  358

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.GemTrafficDescriptor.{i}. */
#define MDMOID_GEM_TRAFFIC_DESCRIPTOR  359

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General. */
#define MDMOID_GENERAL  360

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.UniG.{i}. */
#define MDMOID_UNI_G  361

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.OltG. */
#define MDMOID_OLT_G  362

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.NetworkAddress.{i}. */
#define MDMOID_NETWORK_ADDRESS  363

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.AuthenticationSecurityMethod.{i}. */
#define MDMOID_AUTHENTICATION_SECURITY_METHOD  364

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.LargeString.{i}. */
#define MDMOID_LARGE_STRING  365

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData1.{i}. */
#define MDMOID_THRESHOLD_DATA1  366

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData2.{i}. */
#define MDMOID_THRESHOLD_DATA2  367

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.Omci. */
#define MDMOID_OMCI  368

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.TR069ManagementServer.{i}. */
#define MDMOID_TR069_MANAGEMENT_SERVER  369

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_OmciSystem. */
#define MDMOID_OMCI_SYSTEM  370

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_GponOmciStats. */
#define MDMOID_GPON_OMCI_STATS  371

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WlanNvram. */
#define MDMOID_WLAN_NVRAM  372

/*! \brief InternetGatewayDevice.X_CT_OAM. */
#define MDMOID_CTOAM  373

/*! \brief InternetGatewayDevice.X_CT_OAM.IADInfo. */
#define MDMOID_OAMIAD_INFO  374

/*! \brief InternetGatewayDevice.X_CT_OAM.GlobalParameterConfig. */
#define MDMOID_OAM_GLB_PARAM_CFG  375

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPParameterConfig. */
#define MDMOID_OAMSIP_PARAM_CFG  376

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPUserParameterConfig. */
#define MDMOID_OAMSIP_USR_PARAM_CFG  377

/*! \brief InternetGatewayDevice.X_CT_OAM.FAXModemConfig. */
#define MDMOID_OAMFAXMD_CFG  378

/*! \brief InternetGatewayDevice.X_CT_OAM.POTSStatus. */
#define MDMOID_OAMPOTS_STS  379

/*! \brief InternetGatewayDevice.X_CT_OAM.IADOperation. */
#define MDMOID_OAMIAD_OP  380

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPDigitMap. */
#define MDMOID_OAMSIP_DGT_MP  381

/*! \brief InternetGatewayDevice.SoftwareModules. */
#define MDMOID_SW_MODULES  382

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}. */
#define MDMOID_EU  383

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}.Extensions. */
#define MDMOID_EXTENSIONS  384

/*! \brief InternetGatewayDevice.SoftwareModules.ExecEnv.{i}. */
#define MDMOID_EXEC_ENV  385

/*! \brief InternetGatewayDevice.SoftwareModules.DeploymentUnit.{i}. */
#define MDMOID_DU  386

/*! \brief InternetGatewayDevice.Device. */
#define MDMOID_DEVICE  387

/*! \brief InternetGatewayDevice.Device.Optical. */
#define MDMOID_DEVICE_OPTICAL  388

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}. */
#define MDMOID_OPTICAL_INTERFACE  389

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}.Stats. */
#define MDMOID_OPTICAL_INTERFACE_STATS  390

/*! \brief maximum OID value */
#define MDM_MAX_OID 390



#endif /* __MDM_OBJECTID_H__ */
