MENU_DEVICE_INFO             =  0
MENU_DEVICE_SUMMARY          =  1
MENU_STATISTICS              =  3
MENU_ST_LAN                  =  4
MENU_WAN                     = 12
MENU_DIAGNOSTICS             = 29
MENU_MANAGEMENT              = 30
MENU_TL_SYSTEM_LOG           = 31
MENU_TL_SNMP                 = 32
MENU_TL_UPDATE_SOFTWARE      = 33
MENU_TL_SETTINGS             = 34
MENU_TL_SETTINGS_BACKUP      = 35
MENU_TL_SETTINGS_UPDATE      = 36
MENU_TL_SETTINGS_DEFAULT     = 37
MENU_RESET_ROUTER            = 48
MENU_ACC_CNTR                = 49
MENU_ACC_CNTR_PASSWORD       = 52
MENU_SNTP                    = 55
MENU_TR69C                   = 68
MENU_DIAGP8021AG             = 86
MENU_OMCI_CFG                = 87
MENU_OMCI_GET_SET            = 88
MENU_OMCI_CREATE             = 89
MENU_OMCI_GET_NEXT           = 90
MENU_OMCI_MACRO              = 91
MENU_OMCI_DOWNLOAD           = 92
MENU_OMCI_SYSTEM             = 93
MENU_TL_SECURITY_LOG         = 111
MENU_OPTICAL                 = 125
MENU_XAVI_XMLPROV_DEF        = 126
MENU_XAVI_LOGOUT             = 127
MENU_XAVI_IGMP               = 128
MENU_XAVI_VLAN               = 129
MENU_XAVI_QOS_LIST           = 130
MENU_XAVI_CATV               = 131
MENU_XAVI_PORT_MODE          = 132
MENU_XAVI_QINQ               = 133
MENU_XAVI_RATE_LIMITING      = 134
MENU_XAVI_PORT_POWER         = 135
MENU_XAVI_JUMBO_MODE         = 136
MENU_XAVI_PORT_PROTECT       = 137
MENU_XAVI_ACC_CNTR_IP_ADDR   = 138
MENU_XAVI_ACC_CNTR_SERVICE   = 139
MENU_XAVI_WAN_IF_TYPE        = 140
MENU_XAVI_ADVANCED_SETUP     = 141
MENU_XAVI_8021p_QOS          = 142
MENU_XAVI_WAN_SETTINGS       = 143
MENU_XAVI_LAN_SETTINGS       = 144
MENU_XAVI_LED_MODE           = 145

var menuTitle = new Array();
menuTitle[MENU_DEVICE_INFO]                           = 'Device Info';
menuTitle[MENU_DEVICE_SUMMARY]                        = 'Summary';
menuTitle[MENU_STATISTICS]                            = 'Statistics';
menuTitle[MENU_ST_LAN]                                = 'LAN';
menuTitle[MENU_WAN]                                   = 'WAN';
menuTitle[MENU_DIAGNOSTICS]                           = 'Diagnostics';
menuTitle[MENU_MANAGEMENT]                            = 'Management';
menuTitle[MENU_TL_SYSTEM_LOG]                         = 'System Log';
menuTitle[MENU_TL_SNMP]                               = 'SNMP Agent';
menuTitle[MENU_TL_UPDATE_SOFTWARE]                    = 'Update Software';
menuTitle[MENU_TL_SETTINGS]                           = 'Settings';
menuTitle[MENU_TL_SETTINGS_BACKUP]                    = 'Backup';
menuTitle[MENU_TL_SETTINGS_UPDATE]                    = 'Update';
menuTitle[MENU_TL_SETTINGS_DEFAULT]                   = 'Restore Default';
menuTitle[MENU_RESET_ROUTER]                          = 'Reboot';
menuTitle[MENU_ACC_CNTR]                              = 'Access Control';
menuTitle[MENU_ACC_CNTR_PASSWORD]                     = 'Passwords';
menuTitle[MENU_SNTP]                                  = 'Internet Time';
menuTitle[MENU_TR69C]                                 = 'TR-069 Client';
menuTitle[MENU_DIAGP8021AG]                           = 'Fault Management';
menuTitle[MENU_OMCI_CFG]                              = 'OMCI Configuration';
menuTitle[MENU_OMCI_GET_SET]                          = 'Get/Set/Reboot';
menuTitle[MENU_OMCI_CREATE]                           = 'Create';
menuTitle[MENU_OMCI_GET_NEXT]                         = 'Get Next';
menuTitle[MENU_OMCI_MACRO]                            = 'Macro';
menuTitle[MENU_OMCI_DOWNLOAD]                         = 'Download';
menuTitle[MENU_OMCI_SYSTEM]                           = 'System';
menuTitle[MENU_TL_SECURITY_LOG]                       = 'Security Log';
menuTitle[MENU_OPTICAL]                               = 'Optical';
menuTitle[MENU_XAVI_XMLPROV_DEF]                      = 'Provisioning';
menuTitle[MENU_XAVI_LOGOUT]                           = 'Logout';
menuTitle[MENU_XAVI_IGMP]                             = 'IGMP Snooping';
menuTitle[MENU_XAVI_VLAN]                             = 'VLAN Configuration';
menuTitle[MENU_XAVI_QOS_LIST]                         = 'QoS';
menuTitle[MENU_XAVI_CATV]                             = 'CATV';
menuTitle[MENU_XAVI_PORT_MODE]                        = 'Port Mode';
menuTitle[MENU_XAVI_QINQ]                             = 'QinQ';
menuTitle[MENU_XAVI_RATE_LIMITING]                    = 'Rate Limiting';
menuTitle[MENU_XAVI_PORT_POWER]                       = 'Port Disable/Enable';
menuTitle[MENU_XAVI_JUMBO_MODE]                       = 'Jumbo Frames';
menuTitle[MENU_XAVI_PORT_PROTECT]                     = 'Port Protect';
menuTitle[MENU_XAVI_ACC_CNTR_IP_ADDR]                 = 'IP Addresses';
menuTitle[MENU_XAVI_ACC_CNTR_SERVICE]                 = 'Services';
menuTitle[MENU_XAVI_WAN_IF_TYPE]                      = 'WAN Interface Type';
menuTitle[MENU_XAVI_ADVANCED_SETUP]                   = 'Advanced Setup';
menuTitle[MENU_XAVI_8021p_QOS]                        = '802.1p Priority';
menuTitle[MENU_XAVI_WAN_SETTINGS]                     = 'WAN Setting';
menuTitle[MENU_XAVI_LAN_SETTINGS]                     = 'LAN Setting';
menuTitle[MENU_XAVI_LED_MODE]                         = 'LED Blink Config';

function getMenuTitle(index) {
   return menuTitle[index];
}
