dynamic: install


all: install


install:
	cp -f libwlbcmcrypto.so_XG6846_ITT_save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_XG6846_ITT_save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f nvram_params_XG6846_ITT_save $(INSTALL_DIR)/etc/wlan/nvram_params
